spring:
  application:
    name: web_tlisas_management
  datasource:
    url: jdbc:mysql://localhost:3306/tlisas
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  banner:
    charset: GBK

mybatis:
  mapper-locations: classpath:com/iheima/mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

aliyun:
  oss:
    endpoint: https://oss-us-west-1.aliyuncs.com
    bucket-name: sherry-java-dev
    region: us-west-1



